export const GET_PROJECT_NAME = 'GET_PROJECT_NAME'
export const SET_PROJECT_NAME = 'SET_PROJECT_NAME'

export const ADD_VIEW = 'ADD_VIEW'
export const DELETE_VIEW = 'DELETE_VIEW'

export const SWITCH_PLATFORM_VIEW = 'SWITCH_PLATFORM_VIEW'

export const ADD_COMPONENT = 'ADD_COMPONENT'
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT'
export const DELETE_COMPONENT = 'DELETE_COMPONENT'
export const SELECT_COMPONENT = 'SELECT_COMPONENT'
export const REPLACE_LAYOUT = 'REPLACE_LAYOUT'

export const GENERATE_CODE = 'GENERATE_CODE'
export const GENERATE_CODE_SUCCESS = 'GENERATE_CODE_SUCCESS'
export const GENERATE_CODE_FAIL = 'GENERATE_CODE_FAIL'

export const START_SERVERS = 'START_SERVERS'
export const START_SERVERS_SUCCESS = 'START_SERVERS_SUCCESS'
export const START_SERVERS_FAIL = 'START_SERVERS_FAIL'

export const KILL_SERVERS = 'KILL_SERVERS'
export const KILL_SERVERS_SUCCESS = 'KILL_SERVERS_SUCCESS'
export const KILL_SERVERS_FAIL = 'KILL_SERVERS_FAIL'

export const CHECK_SERVERS_STARTED = 'CHECK_SERVERS_STARTED'
export const CHECK_SERVERS_STARTED_SUCCESS = 'CHECK_SERVERS_STARTED_SUCCESS'
