export const GET_PROJECT_NAME = 'GET_PROJECT_NAME'
export const SET_PROJECT_NAME = 'SET_PROJECT_NAME'

export const ADD_VIEW = 'ADD_VIEW'
export const DELETE_VIEW = 'DELETE_VIEW'

export const SWITCH_PLATFORM_VIEW = 'SWITCH_PLATFORM_VIEW'

export const ADD_COMPONENT = 'ADD_COMPONENT'
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT'
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT'
export const REPLACE_LAYOUT = 'REPLACE_LAYOUT'

export const GENERATE_CODE = 'GENERATE_CODE'
export const GENERATE_CODE_SUCCESS = 'GENERATE_CODE_SUCCESS'
export const GENERATE_CODE_FAIL = 'GENERATE_CODE_FAIL'
