const GENERATE_CODE = 'GENERATE_CODE'
const START_PROJECT = 'START_PROJECT'
const KILL_PROJECT = 'KILL_PROJECT'
const CHECK_SERVERS_STARTED = 'CHECK_SERVERS_STARTED'

module.exports = {
  GENERATE_CODE,
  START_PROJECT,
  KILL_PROJECT,
  CHECK_SERVERS_STARTED,
}
